/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.17
 * Generated at: 2019-04-15 08:03:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import kr.or.kosta.utils.Singleton_Helper;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.Connection;

public final class Ex02_005fJDBC_005floginok_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("kr.or.kosta.utils.Singleton_Helper");
    _jspx_imports_classes.add("java.sql.Connection");
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("java.sql.PreparedStatement");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

 /*  
 1. 한글처리
 2. 데이터 받기(ID, PWD)
 3. DB 연동(sql)
 4. 업무(로직) 처리
 
    id, pwd 를 parameter 로 받아서 회원인지 아닌지 판단
    
    --판단조건
    1.ID 존재 , PWD(0) > 회원 > Main page 이동 > session.setAttribute("userid",ID값); 
    2.ID 존재 , PWD(x) > 다시 한번 로그인 처리 (로그인 페이지)
    3.ID 존재(x) > 회원가입 페이지로 이동 처리
    
    1.Ex02_JDBC_Main.jsp
    2.Ex02_JDBC_Login.jsp
    3.Ex02_JDBC_JoinForm.jsp
    
    >sql : select id, pwd  from koreamember where id=?
    >(x)sql : select count from koreamember where id=?	
    		
    >>SELECT ..... 		
    1. 결과	없는 경우
    
    2. Single row
    
    3. Multi row (회원데이터)
    
    if(rs.next()){
    	 do{
    		 System.out.println(rs.getInt(1));
    	 }while(rs.next());
    }else{
    	회원이 아닌 경우
    }
    
    요구사항 
    https://cafe.naver.com/kangnamfullstack/665
  
    기능적 요구사항
    로그인이 가능
    ...
    비기능적 요구사항
    SingletonHelper 을 사용해서 코드 중복성을 줄인다 
 */
 request.setCharacterEncoding("UTF-8");
	
	//2. 데이터 받기
	String id = request.getParameter("id");
	String pwd = request.getParameter("pwd");
	
	
	//Class.forName("oracle.jdbc.OracleDriver");
	Connection   conn = null;
 	PreparedStatement pstmt = null;
 	ResultSet rs = null;
 
 try{
	
 	//conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","kosta","1004");;
 	conn = Singleton_Helper.getConnection("oracle");
 	String sql = "select id,pwd from koreamember where id=?";
 	pstmt = conn.prepareStatement(sql);
 	pstmt.setString(1,id);
 	rs = pstmt.executeQuery();
 	
 	while(rs.next()){
 		
 		//ID존재
 		if(pwd.equals(rs.getString("pwd"))){
 			//ID(0) , PWD(0)
 			//정상회원
 			
 			//Top.jsp 활용
 			session.setAttribute("userid", rs.getString("id"));
 			
 			out.print("<script>");
 				out.print("location.href='Ex02_JDBC_Main.jsp'");
 			out.print("</script>");
 		}else{
 			//ID(0) , PWD(x)
 				out.print("<script>");
					out.print("location.href='Ex02_JDBC_Login.jsp'");
				out.print("</script>");
 		}
 	}
 		//ID(x)
 		out.print("<script>");
			out.print("location.href='Ex02_JDBC_JoinForm.jsp'");
		out.print("</script>");
 	
 }catch(Exception e){
 	e.printStackTrace();
 }finally{
 	System.out.println("Finally");
 	Singleton_Helper.close(rs);
 	Singleton_Helper.close(pstmt);
		//연결은 해제 하지 않아요 ....
 }


    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
